//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNov14.SqlDataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class DataBaseSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataBaseSettings defaultInstance = ((DataBaseSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataBaseSettings())));
        
        public static DataBaseSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=DESKTOP-UMF5E2J\\\\SQLEXPRESS;Database=VestPlastDatabase;MultipleActiveResul" +
            "tSets=true;User ID=VPApplication;Password=AreleaApp#ConnPass")]
        public string DesktopConnectionString {
            get {
                return ((string)(this["DesktopConnectionString"]));
            }
        }
    }
}
